# Generated by Django 3.0.8 on 2020-08-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200822_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_creted',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_creted',
            new_name='date_created',
        ),
    ]
